:imagesdir: images
:couchbase_version: current
:toc:
:project_id: abevjava-on-arm
:icons: font
:source-highlighter: prettify
:tags: guides,meta

= abevjava-armv8

Abevjava futtatása Macbook Mx processzorral.

:sectnums!:
== Előfeltételek

* XQuartz https://www.xquartz.org[letöltése és telepítése] (futtatni a .pkg kiterjesztésű fájlt)
** Telepítés után indítsuk el az XQuartz alkalmazást és a menüben az XQuartz/Settings.../Security menüpont alatt tegyünk egy pipát az 'Allow connections from network clients' mellé.

* Docker https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-arm64[letöltése és telepítése]

* Git repo le legyen töltve a saját gépünkre

** Nyissunk egy terminal ablakot (CMD+Space és kezdjük el gépelni, hogy terminal)
 
 cd Downloads
 git clone https://github.com/cserhatit/abevjava-armv8 
 
== Telepítés
* Telepítsük az ÁNYK-t 

https://nav.gov.hu/nyomtatvanyok/letoltesek/nyomtatvanykitolto_programok/nyomtatvany_apeh/keretprogramok/AbevJava[ÁNYK letöltése]

A telepítés helye a home könyvtárban legyen az abevjava/abevjava-keret alá.
 
  /Users/sajat.user/abevjava/abevjava-keret

A nyomtatványoknak az alábbi könyvtárat állítsuk be:

  /Users/sajat.user/abevjavafiles

* A számítógépünkön hozzuk létre a következő könyvtárat (ha nem lenne):

** /tmp/.X11-unix

[WARNING]
====
Ez elvileg egy már létező könyvtár, de ha mégsem, akkor adjuk ki itt is az mkdir parancsot:

  mkdir /tmp/.X11-unix

====

* Menjünk abba a könyvtárba, ahová letöltöttük a fájlokat ebből a git repositoryból.

 példánkban: cd ~/Downloads/abevjava-armv8
 
== Futtatás

* Futtassuk le az abevjava.sh fájlt:

 ~/Downloads/abevjava.sh

[TIP]
====
Egy aliast is létrehozhatunk a gépen:

nyissunk egy terminal ablakot, és adjuk hozzá a .zshrc fájl végéhez - új sorban természetesen - a következőt:
 
 alias abevjava="~/Downloads/abevjava.sh"
 alias abev="abevjava"

ezután ha új terminal ablakot nyitunk, akkor `abev` vagy `abevjava` paranccsal is indítható lesz az alkalmazás.

====
